global:
 resolve_timeout: 1m
 smtp_smarthost: 'smtp.gmail.com:587'
 smtp_from: 'hirayamanawariautomation@gmail.com'
 smtp_auth_username: 'hirayamanawariautomation@gmail.com'
 smtp_auth_password: 'knnkyiovubzwrkwv'
 smtp_require_tls: true

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'deguzmancaptain@gmail.com'
    from: 'hirayamanawariautomation@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'hirayamanawariautomation@gmail.com'
    auth_identity: 'hirayamanawariautomation@gmail.com'
    auth_password: '<password>'
    send_resolved: true
    require_tls: true


inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
