global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['localhost:9100']
      - targets: ['172.31.37.11:9100']

rule_files:
  - 'alerting.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093 
